// Author:      machinageist
// Date:        2026-04
// Description: Handlers for blog routes: post list and single post view.
//              list() scans content/posts/, loads all BlogPost structs sorted
//              newest-first, and renders blog_list.html.
//              post() extracts the :slug path parameter, validates it against
//              path traversal patterns, loads the matching .md file, and renders
//              blog_post.html with the Markdown already converted to HTML.
//              Both return Result<_, SiteError> so the ? operator propagates
//              file I/O errors up to IntoResponse for clean HTTP error pages.
//
// Notes:       Path traversal defense — slug validation is the first thing
//              post() does before any filesystem access. Two layers:
//                1. Explicit check rejects slugs containing / \ or ..
//                2. BlogPost::find() constructs the path itself — user input
//                   never controls the directory, only the filename portion.
//              The |safe filter in blog_post.html is safe here because
//              content_html is generated by pulldown-cmark from our own .md
//              files — never from user-supplied input.

use askama::Template;
use askama_axum::IntoResponse;
use axum::extract::Path;
use std::path::PathBuf;
use crate::models::post::BlogPost;
use crate::errors::SiteError;

// Canonical path to posts directory — single definition prevents typo drift
const POSTS_DIR: &str = "content/posts";

// -----------------------------------------------------------------------
// Blog list page — blog_list.html
// -----------------------------------------------------------------------

#[derive(Template)]
#[template(path = "blog_list.html")]
pub struct BlogListTemplate {
    // Vec sorted newest-first by BlogPost::load_all()
    pub posts: Vec<BlogPost>,
}

impl BlogListTemplate {
    // Supply page title to base.html <title> slot
    pub fn title(&self) -> &str { "writing" }
}

// Scan posts directory, load all posts, render index page
pub async fn list() -> Result<impl IntoResponse, SiteError> {
    let posts_dir = PathBuf::from(POSTS_DIR);
    // ? propagates SiteError::Io if directory read fails
    let posts = BlogPost::load_all(&posts_dir)?;
    Ok(BlogListTemplate { posts })
}

// -----------------------------------------------------------------------
// Single post page — blog_post.html
// -----------------------------------------------------------------------

#[derive(Template)]
#[template(path = "blog_post.html")]
pub struct BlogPostTemplate {
    pub post: BlogPost,
}

impl BlogPostTemplate {
    // Use post title as page title — populated from frontmatter
    pub fn title(&self) -> &str { &self.post.title }
}

// Extract slug from URL, validate, load matching post file, render page
// Path(slug) — Axum extracts the :slug segment and binds it to `slug`
pub async fn post(Path(slug): Path<String>) -> Result<impl IntoResponse, SiteError> {
    // Reject slugs that could escape the posts directory
    // Prevents: GET /blog/../../etc/passwd → reading arbitrary files
    if slug.contains('/') || slug.contains('\\') || slug.contains("..") {
        return Err(SiteError::PostNotFound(slug));
    }

    let posts_dir = PathBuf::from(POSTS_DIR);
    // ? returns 404 via SiteError::PostNotFound if file doesn't exist
    let post = BlogPost::find(&posts_dir, &slug)?;
    Ok(BlogPostTemplate { post })
}
