// Author:      machinageist
// Date:        2026-04
// Description: Handlers for blog routes: post list and single post view.
//              list() scans content/posts/, loads all BlogPost structs sorted
//              newest-first, and renders blog_list.html.
//              post() extracts the :slug path parameter, validates it against
//              path traversal patterns, loads the matching .md file, and renders
//              blog_post.html with the Markdown already converted to HTML.
//              Both return Result<_, SiteError> so the ? operator propagates
//              file I/O errors up to IntoResponse for clean HTTP error pages.
//
// Notes:       Path traversal defense — slug validation is the first thing
//              post() does before any filesystem access. Two layers:
//                1. Explicit check rejects slugs containing / \ or ..
//                2. BlogPost::find() constructs the path itself — user input
//                   never controls the directory, only the filename portion.
//              The |safe filter in blog_post.html is safe here because
//              content_html is generated by pulldown-cmark from our own .md
//              files — never from user-supplied input.

use crate::errors::SiteError;
use crate::models::post::BlogPost;
use askama::Template;
use askama_axum::IntoResponse;
use axum::extract::Path;
use std::path::PathBuf;

// Canonical path to posts directory — single definition prevents typo drift
// pub(crate) so the home page can pull its "latest writing" list from the same path
pub(crate) const POSTS_DIR: &str = "content/posts";

// Portfolio pillars, in display order. A post's `category` frontmatter field is
// matched against these to group the blog list. Posts with no category (or a
// category outside this set) fall into the trailing "Other writing" group.
const PILLARS: &[&str] = &[
    "Homelab & Proxmox",
    "Networking",
    "Linux / SysAdmin",
    "Security",
];

// Heading for posts that do not belong to a named pillar
const OTHER_GROUP: &str = "Other writing";

// -----------------------------------------------------------------------
// Blog list page — blog_list.html
// -----------------------------------------------------------------------

// One pillar section in the grouped blog list
pub struct PostGroup {
    pub label: String,
    pub posts: Vec<BlogPost>,
}

#[derive(Template)]
#[template(path = "blog_list.html")]
pub struct BlogListTemplate {
    // Non-empty pillar groups in PILLARS order, then "Other writing"
    pub groups: Vec<PostGroup>,
}

impl BlogListTemplate {
    // Supply page title to base.html <title> slot
    pub fn title(&self) -> &str {
        "Writing — machinageist"
    }
    pub fn description(&self) -> &str {
        "Notes on the homelab, networking, Linux, and defensive security by machinageist — mostly what broke and how it got fixed."
    }
    pub fn section(&self) -> &str {
        "writing"
    }
}

// Scan posts directory, load all posts, group them by pillar, render index page
pub async fn list() -> Result<impl IntoResponse, SiteError> {
    let posts_dir = PathBuf::from(POSTS_DIR);
    // ? propagates SiteError::Io if directory read fails
    let posts = BlogPost::load_all(&posts_dir)?;
    Ok(BlogListTemplate {
        groups: group_by_pillar(posts),
    })
}

// Bucket posts into pillar groups (PILLARS order) plus a trailing "Other writing"
// group; drop empty groups. Input order (newest-first) is preserved within each.
fn group_by_pillar(posts: Vec<BlogPost>) -> Vec<PostGroup> {
    let mut groups: Vec<PostGroup> = Vec::new();

    for &pillar in PILLARS {
        let matched: Vec<BlogPost> = posts
            .iter()
            .filter(|p| p.category.as_deref() == Some(pillar))
            .cloned()
            .collect();
        if !matched.is_empty() {
            groups.push(PostGroup {
                label: pillar.to_string(),
                posts: matched,
            });
        }
    }

    // Anything without a recognized pillar category lands here
    let other: Vec<BlogPost> = posts
        .into_iter()
        .filter(|p| match p.category.as_deref() {
            Some(c) => !PILLARS.contains(&c),
            None => true,
        })
        .collect();
    if !other.is_empty() {
        groups.push(PostGroup {
            label: OTHER_GROUP.to_string(),
            posts: other,
        });
    }

    groups
}

// -----------------------------------------------------------------------
// Single post page — blog_post.html
// -----------------------------------------------------------------------

#[derive(Template)]
#[template(path = "blog_post.html")]
pub struct BlogPostTemplate {
    pub post: BlogPost,
}

impl BlogPostTemplate {
    // Use post title as page title — populated from frontmatter
    pub fn title(&self) -> &str {
        &self.post.title
    }
    pub fn description(&self) -> &str {
        &self.post.summary
    }
    pub fn section(&self) -> &str {
        "writing"
    }
}

// Extract slug from URL, validate, load matching post file, render page
// Path(slug) — Axum extracts the :slug segment and binds it to `slug`
pub async fn post(Path(slug): Path<String>) -> Result<impl IntoResponse, SiteError> {
    // Reject slugs that could escape the posts directory
    // Prevents: GET /blog/../../etc/passwd → reading arbitrary files
    if slug.contains('/') || slug.contains('\\') || slug.contains("..") {
        return Err(SiteError::PostNotFound(slug));
    }

    let posts_dir = PathBuf::from(POSTS_DIR);
    // ? returns 404 via SiteError::PostNotFound if file doesn't exist
    let post = BlogPost::find(&posts_dir, &slug)?;
    Ok(BlogPostTemplate { post })
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::NaiveDate;

    // Build a minimal post carrying only the fields grouping cares about
    fn post(slug: &str, category: Option<&str>) -> BlogPost {
        BlogPost {
            slug: slug.to_string(),
            title: slug.to_string(),
            date: NaiveDate::from_ymd_opt(2026, 1, 1).unwrap(),
            summary: String::new(),
            tags: Vec::new(),
            category: category.map(str::to_string),
            content_html: String::new(),
        }
    }

    #[test]
    fn grouping_orders_pillars_and_collects_the_rest_under_other() {
        let posts = vec![
            post("uncategorized", None),
            post("net-a", Some("Networking")),
            post("sec-a", Some("Security")),
            post("unknown-pillar", Some("Nonsense")),
        ];

        let groups = group_by_pillar(posts);
        let labels: Vec<&str> = groups.iter().map(|g| g.label.as_str()).collect();

        // Pillars appear in PILLARS order; empty pillars are dropped; Other is last
        assert_eq!(labels, vec!["Networking", "Security", OTHER_GROUP]);

        // Both the None post and the non-pillar category land in Other
        let other = groups.last().unwrap();
        assert_eq!(other.posts.len(), 2);
    }
}
